# Generated by Django 4.2.2 on 2023-10-10 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChargeHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("head_code", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "head_value_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "has_rules",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("unit_labels", models.CharField(max_length=150, null=True)),
                ("value", models.CharField(max_length=50)),
                (
                    "currency_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("perform", models.CharField(blank=True, max_length=100, null=True)),
                ("max_value", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "static_percentage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "min_static_cost",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="product.chargehead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Charges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("based_on", models.CharField(blank=True, max_length=100, null=True)),
                ("base", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "any_condition",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("local", models.FloatField(default=0, null=True)),
                ("international", models.FloatField(default=0, null=True)),
                ("minimum_cost", models.FloatField(default=0, null=True)),
                ("static_cost", models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChargeHeadRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min", models.FloatField()),
                ("max", models.FloatField(null=True)),
                (
                    "head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.chargehead",
                    ),
                ),
            ],
        ),
    ]
